remote_theme: daattali/beautiful-jekyll

title: Habib Tech
author: Habib

navbar-links:
  Services: "/#services"
  About Us: "/#aboutus"
  Clients: "/#clients"
  Open-Source: "/#portfolio"
  Contact Us: "/contact"

title-img: /assets/img/habibtech-logo-light.png

site-css: "/assets/css/habibtech.css"

keywords: "habibur, habib's,Habib, habibur rahaman,"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "habiburhub@gmail.com"
  facebook: habibsuite
  github: habibhub
  twitter: arlinakiky

url-pretty: "Habib Tech"

footer-img: "/assets/img/footer-bg.png"

# gtag: ""

timezone: "India/Kolkata"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "Welcome to Habib's collection on Religion, Astronomy, Mathematics, Technology, Hobbies and Everything I finds interesting."
      share-img: "/assets/img/habibtech.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# 2fc73a3a967e97599c9763d05e564189